# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
  autoCancel: true
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string

jobs:
- job: publish_runtime_container
  condition: eq(variables['build.sourceBranch'], 'refs/heads/master')
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    dockerId: ai4edrivendata
    imageName: inference
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 90
  steps:
  - script: |
      echo $(Build.SourceVersion)
      cd runtime
      docker build -t $(dockerId).azurecr.io/$(imageName):$(Build.SourceVersion) .
      docker login -u $(dockerId) -p $(dockerPassword) $(dockerId).azurecr.io
      docker push $(dockerId).azurecr.io/$(imageName):$(Build.SourceVersion)
    displayName: 'Build and deploy Docker container'
- job: test_gpu_installs
  condition: ne(variables['build.sourceBranch'], 'refs/heads/master')
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    dockerId: ai4edrivendata
    imageName: inference
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 90
  steps:
  - script: |
      cd runtime
      docker build --build-arg CPU_GPU=gpu -t $(dockerId)/$(imageName):$(Build.SourceVersion) .
      docker run $(dockerId)/$(imageName):$(Build.SourceVersion) /bin/bash -c "bash run-tests.sh"
    displayName: 'Test installs for GPU environment'
- job: test_cpu_installs
  condition: ne(variables['build.sourceBranch'], 'refs/heads/master')
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    dockerId: ai4edrivendata
    imageName: inference
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 90
  steps:
  - script: |
      cd runtime
      docker build --build-arg CPU_GPU=cpu -t $(dockerId)/$(imageName):$(Build.SourceVersion) .
      docker run $(dockerId)/$(imageName):$(Build.SourceVersion) /bin/bash -c "bash run-tests.sh"
    displayName: 'Test installs for CPU environment'
