# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
variables:
  dockerId: ai4edrivendata
  imageName: inference

jobs:
- job: Build Runtime Docker Container
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 90
  steps:
  - script: |
      docker build -t $(dockerId).azurecr.io/$(imageName) .
      docker login -u $(dockerId) -p $(dockerPassword) $(dockerId).azurecr.io
      docker push $(dockerId).azurecr.io/$(imageName)
    env:
      pswd: $(dockerPassword)        
