# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: build_runtime_container
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    dockerId: ai4edrivendata
    imageName: inference
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 90
  steps:
  - script: |
      T=$(git rev-parse --short HEAD) echo $T
      docker build -t $(dockerId).azurecr.io/$(imageName):$T .
      docker login -u $(dockerId) -p $(dockerPassword) $(dockerId).azurecr.io
      docker push $(dockerId).azurecr.io/$(imageName):$(git rev-parse --short HEAD)
    env:
      GIT_COMMIT: $(Build.SourceVersion)
